/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package old;

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JList;

import components.ArticoloDataDialog;
import components.ArticoloDialog;
import components.IngressoDataDialog;
import components.IngressoDialog;
import components.UscitaDataDialog;
import components.UscitaDialog;
import containers.Magazzino;
import controllers.MagazzinoController;
import models.Ingresso;
import models.Uscita;

/**
 *
 * @author hartmann
 */
public class MagazzinoView extends javax.swing.JFrame {

	private MagazzinoController controller;
	
	private javax.swing.JList<String> articoliList;
    private javax.swing.JScrollPane articoliScroll;
    
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton ingressiButton;
    private javax.swing.JList<String> ingressiList;
    private javax.swing.JScrollPane ingressiScroll;
    private IngressoDataDialog ingressoDataDialog;
    private UscitaDataDialog uscitaDataDialog;
    private ArticoloDataDialog articoloDataDialog;
    private javax.swing.JLabel magazzinoLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton usciteButton;
    private javax.swing.JList<String> usciteList;
    private javax.swing.JScrollPane usciteScroll;
	
    /**
     * Creates new form MagazzinoView
     */
    public MagazzinoView() {
        initComponents();
        controller = new MagazzinoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        //ingressoDataDialog = new IngressoDataDialog();
        uscitaDataDialog = new UscitaDataDialog();
        articoloDataDialog = new ArticoloDataDialog();
        titlePanel = new javax.swing.JPanel();
        magazzinoLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        ingressiScroll = new javax.swing.JScrollPane();
        ingressiList = new javax.swing.JList<>();
        articoliScroll = new javax.swing.JScrollPane();
        articoliList = new javax.swing.JList<>();
        usciteScroll = new javax.swing.JScrollPane();
        usciteList = new javax.swing.JList<>();
        ingressiButton = new javax.swing.JButton();
        usciteButton = new javax.swing.JButton();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        magazzinoLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        magazzinoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magazzinoLabel.setText("Magazzino");
        magazzinoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(magazzinoLabel)
                .addGap(321, 321, 321))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(magazzinoLabel)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        contentPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(0, 0, 0), null, null));

        ingressiList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = (String[]) Magazzino.getInstance().getIngressi().keySet().toArray();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ingressiScroll.setViewportView(ingressiList);

        articoliList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = (String[]) Magazzino.getInstance().getArticoli().keySet().toArray();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        articoliScroll.setViewportView(articoliList);

        usciteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = (String[]) Magazzino.getInstance().getUscite().keySet().toArray();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        usciteScroll.setViewportView(usciteList);

        ingressiButton.setText("Add Ingresso");
        ingressiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.ingressiButtonActionPerformed(evt).setVisible(true);
            }
        });

        usciteButton.setText("Add Uscita");
        usciteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.usciteButtonActionPerformed(evt);
            }
        });

        ingressiList.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent mouseEvent) {
                if (mouseEvent.getClickCount() == 2) {
                  int index = ((JList<String>)mouseEvent.getSource()).locationToIndex(mouseEvent.getPoint());
                  if (index >= 0) {
                    String str = ((JList<String>)mouseEvent.getSource()).getModel().getElementAt(index);
                    Ingresso ingresso = Magazzino.getInstance().getIngressi().get(str);
                    //ingressoDataDialog.setData(ingresso.getArticolo().getUnicode(), ingresso.getIngrUnicode(), ingresso.getIngrDate(), ingresso.getNumMensola());
                    ingressoDataDialog.setVisible(true);
                  }
                }
              }
        });
        
        usciteList.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent mouseEvent) {
                if (mouseEvent.getClickCount() == 2) {
                  int index = ((JList<String>)mouseEvent.getSource()).locationToIndex(mouseEvent.getPoint());
                  if (index >= 0) {
                    String str = ((JList<String>)mouseEvent.getSource()).getModel().getElementAt(index);
                    Uscita uscita = Magazzino.getInstance().getUscite().get(str);
                    uscitaDataDialog.setData(uscita.getArticolo().getUnicode(), uscita.getUscBolla(), uscita.getUscDate(), uscita.getNegozio().getCodFiscale(), uscita.getSpedizioniere());
                    uscitaDataDialog.setVisible(true);
                  }
                }
              }
        });
        
        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ingressiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(ingressiScroll))
                .addGap(65, 65, 65)
                .addComponent(articoliScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usciteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(usciteScroll))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingressiScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(articoliScroll)
                    .addComponent(usciteScroll))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingressiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(usciteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }
}
